apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}-service
  labels:
    app: {{ .Values.postgres.name }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
  type: {{ .Values.postgres.service.type }}
